import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  team,
  analytics,
}: // auth,
{
  children: React.ReactNode;
  team: React.ReactNode;
  analytics: React.ReactNode;
  // auth: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        {team}
        {analytics}
        {/* {auth} */}
      </body>
    </html>
  );
}
